### ISSUE TITLE
Error while auth 503, message='Service Temporarily Unavailable', url=URL('https://ago-api.hexacore.io/api/app-auth

### ISSUE THREAD

**Issue by kamkuakuay** [HiddenCodeDevs/HEXACOREbot#14]
![image](https://github.com/user-attachments/assets/0dd3a61b-0072-463a-9719-91ba57f8ded8)

**Comment by MrTimonM** [comment]
bro, how did you run 10 session all at once?
can you please show how to set up proxies? I have residential proxies with me

**Comment by AlexKrutoy** [comment]
now works
