### ISSUE TITLE
hurt-me-please games skips

### ISSUE THREAD

**Issue by whereispie** [HiddenCodeDevs/HEXACOREbot#15]
As i can see after run of play_game_6 function games counter still 5 in application and nothing going on in app.
In function server sends 2** but it seems that "agoClaimed" maybe wrong. 

Any thoughts on this ? 

in log it's like games are passed, but in real app nothing happens (8:01 games passed by log, 8:04 screen for no games used)
![image](https://github.com/user-attachments/assets/fce78604-752b-46e3-a847-e92580837d22)

![image](https://github.com/user-attachments/assets/e6b9c62a-1e03-47ee-ba01-7f3d5104dfa0)

**Comment by AlexKrutoy** [comment]
now works
